spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/coupon?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-timeout: 3000
      username: abcd
      password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6380
  kafka:
    bootstrap-servers: "localhost:10000,localhost:10001,localhost:10002"

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://PROD_URL/coupon?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-timeout: 3000
      username: PROD_USER_NAME
      password: PROD_PASSWORD
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: PROD_URL
      port: 6380
