global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "coupon-api"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '13.125.1.59:8080' ]
  - job_name: "coupon-consumer"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '54.180.126.48:8081' ]

