spring:
  application:
    name: coupon-consumer

server:
  port: 8081

management:
  metrics:
    tags:
      application:
        ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus
  kafka:
    bootstrap-servers: "localhost:10000,localhost:10001,localhost:10002"
