spring:
  application:
    name: coupon-api
  data:
    redis:
      host: localhost
      port: 6380
  kafka:
    bootstrap-servers: "localhost:10000,localhost:10001,localhost:10002"

server:
  port: 8080
  tomcat:
    mbeanregistry:
      enabled: true
management:
  metrics:
    tags:
      application:
        ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus
